version: "3.9"
services:
  backend:
    container_name: sh-backend
    image: sh-backend
    build:
      context: ./backend
      target: sh-backend
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - db

  db:
    container_name: sh-mongodb
    image: "mongo"
    ports:
      - "27017:27017"

  redis:
    container_name: sh-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --save 60 1 --loglevel warning
